// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Orientation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pitch         float32                `protobuf:"fixed32,1,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Yaw           float32                `protobuf:"fixed32,2,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orientation) Reset() {
	*x = Orientation{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orientation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orientation) ProtoMessage() {}

func (x *Orientation) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orientation.ProtoReflect.Descriptor instead.
func (*Orientation) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *Orientation) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *Orientation) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      *string                `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3,oneof" json:"player_id,omitempty"` // nil = server message
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetPlayerId() string {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Join struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

type JoinAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAck) Reset() {
	*x = JoinAck{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAck) ProtoMessage() {}

func (x *JoinAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAck.ProtoReflect.Descriptor instead.
func (*JoinAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *JoinAck) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PlayerInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MovementDirection *Vector3               `protobuf:"bytes,1,opt,name=movement_direction,json=movementDirection,proto3,oneof" json:"movement_direction,omitempty"`
	CameraOrientation *Orientation           `protobuf:"bytes,2,opt,name=camera_orientation,json=cameraOrientation,proto3,oneof" json:"camera_orientation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerInput) GetMovementDirection() *Vector3 {
	if x != nil {
		return x.MovementDirection
	}
	return nil
}

func (x *PlayerInput) GetCameraOrientation() *Orientation {
	if x != nil {
		return x.CameraOrientation
	}
	return nil
}

type PlayerState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlayerId          string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position          *Vector3               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	CameraOrientation *Orientation           `protobuf:"bytes,3,opt,name=camera_orientation,json=cameraOrientation,proto3" json:"camera_orientation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerState) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerState) GetCameraOrientation() *Orientation {
	if x != nil {
		return x.CameraOrientation
	}
	return nil
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *GameState) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *GameState) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_Join
	//	*ClientEvent_PlayerInput
	//	*ClientEvent_ChatMessage
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetJoin() *Join {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientEvent) GetPlayerInput() *PlayerInput {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_PlayerInput); ok {
			return x.PlayerInput
		}
	}
	return nil
}

func (x *ClientEvent) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_Join struct {
	Join *Join `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientEvent_PlayerInput struct {
	// Leave leave = 2;
	PlayerInput *PlayerInput `protobuf:"bytes,3,opt,name=player_input,json=playerInput,proto3,oneof"`
}

type ClientEvent_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,4,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

func (*ClientEvent_Join) isClientEvent_Event() {}

func (*ClientEvent_PlayerInput) isClientEvent_Event() {}

func (*ClientEvent_ChatMessage) isClientEvent_Event() {}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_JoinAck
	//	*ServerEvent_GameState
	//	*ServerEvent_ChatMessage
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetJoinAck() *JoinAck {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_JoinAck); ok {
			return x.JoinAck
		}
	}
	return nil
}

func (x *ServerEvent) GetGameState() *GameState {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_GameState); ok {
			return x.GameState
		}
	}
	return nil
}

func (x *ServerEvent) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_JoinAck struct {
	JoinAck *JoinAck `protobuf:"bytes,1,opt,name=join_ack,json=joinAck,proto3,oneof"`
}

type ServerEvent_GameState struct {
	// LeaveAck leave_ack = 2;
	GameState *GameState `protobuf:"bytes,3,opt,name=game_state,json=gameState,proto3,oneof"`
}

type ServerEvent_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,4,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

func (*ServerEvent_JoinAck) isServerEvent_Event() {}

func (*ServerEvent_GameState) isServerEvent_Event() {}

func (*ServerEvent_ChatMessage) isServerEvent_Event() {}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"5\n" +
	"\vOrientation\x12\x14\n" +
	"\x05pitch\x18\x01 \x01(\x02R\x05pitch\x12\x10\n" +
	"\x03yaw\x18\x02 \x01(\x02R\x03yaw\"W\n" +
	"\vChatMessage\x12 \n" +
	"\tplayer_id\x18\x01 \x01(\tH\x00R\bplayerId\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\f\n" +
	"\n" +
	"_player_id\"\x06\n" +
	"\x04Join\"&\n" +
	"\aJoinAck\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\xc5\x01\n" +
	"\vPlayerInput\x12A\n" +
	"\x12movement_direction\x18\x01 \x01(\v2\r.game.Vector3H\x00R\x11movementDirection\x88\x01\x01\x12E\n" +
	"\x12camera_orientation\x18\x02 \x01(\v2\x11.game.OrientationH\x01R\x11cameraOrientation\x88\x01\x01B\x15\n" +
	"\x13_movement_directionB\x15\n" +
	"\x13_camera_orientation\"\x97\x01\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12)\n" +
	"\bposition\x18\x02 \x01(\v2\r.game.Vector3R\bposition\x12@\n" +
	"\x12camera_orientation\x18\x03 \x01(\v2\x11.game.OrientationR\x11cameraOrientation\"L\n" +
	"\tGameState\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x12+\n" +
	"\aplayers\x18\x02 \x03(\v2\x11.game.PlayerStateR\aplayers\"\xa8\x01\n" +
	"\vClientEvent\x12 \n" +
	"\x04join\x18\x01 \x01(\v2\n" +
	".game.JoinH\x00R\x04join\x126\n" +
	"\fplayer_input\x18\x03 \x01(\v2\x11.game.PlayerInputH\x00R\vplayerInput\x126\n" +
	"\fchat_message\x18\x04 \x01(\v2\x11.game.ChatMessageH\x00R\vchatMessageB\a\n" +
	"\x05event\"\xac\x01\n" +
	"\vServerEvent\x12*\n" +
	"\bjoin_ack\x18\x01 \x01(\v2\r.game.JoinAckH\x00R\ajoinAck\x120\n" +
	"\n" +
	"game_state\x18\x03 \x01(\v2\x0f.game.GameStateH\x00R\tgameState\x126\n" +
	"\fchat_message\x18\x04 \x01(\v2\x11.game.ChatMessageH\x00R\vchatMessageB\a\n" +
	"\x05event2?\n" +
	"\vGameService\x120\n" +
	"\x04Play\x12\x11.game.ClientEvent\x1a\x11.game.ServerEvent(\x010\x01B+Z)kr1sal.com/build-n-destroy/internal/pb;pbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_game_proto_goTypes = []any{
	(*Vector3)(nil),     // 0: game.Vector3
	(*Orientation)(nil), // 1: game.Orientation
	(*ChatMessage)(nil), // 2: game.ChatMessage
	(*Join)(nil),        // 3: game.Join
	(*JoinAck)(nil),     // 4: game.JoinAck
	(*PlayerInput)(nil), // 5: game.PlayerInput
	(*PlayerState)(nil), // 6: game.PlayerState
	(*GameState)(nil),   // 7: game.GameState
	(*ClientEvent)(nil), // 8: game.ClientEvent
	(*ServerEvent)(nil), // 9: game.ServerEvent
}
var file_game_proto_depIdxs = []int32{
	0,  // 0: game.PlayerInput.movement_direction:type_name -> game.Vector3
	1,  // 1: game.PlayerInput.camera_orientation:type_name -> game.Orientation
	0,  // 2: game.PlayerState.position:type_name -> game.Vector3
	1,  // 3: game.PlayerState.camera_orientation:type_name -> game.Orientation
	6,  // 4: game.GameState.players:type_name -> game.PlayerState
	3,  // 5: game.ClientEvent.join:type_name -> game.Join
	5,  // 6: game.ClientEvent.player_input:type_name -> game.PlayerInput
	2,  // 7: game.ClientEvent.chat_message:type_name -> game.ChatMessage
	4,  // 8: game.ServerEvent.join_ack:type_name -> game.JoinAck
	7,  // 9: game.ServerEvent.game_state:type_name -> game.GameState
	2,  // 10: game.ServerEvent.chat_message:type_name -> game.ChatMessage
	8,  // 11: game.GameService.Play:input_type -> game.ClientEvent
	9,  // 12: game.GameService.Play:output_type -> game.ServerEvent
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_game_proto_msgTypes[2].OneofWrappers = []any{}
	file_game_proto_msgTypes[5].OneofWrappers = []any{}
	file_game_proto_msgTypes[8].OneofWrappers = []any{
		(*ClientEvent_Join)(nil),
		(*ClientEvent_PlayerInput)(nil),
		(*ClientEvent_ChatMessage)(nil),
	}
	file_game_proto_msgTypes[9].OneofWrappers = []any{
		(*ServerEvent_JoinAck)(nil),
		(*ServerEvent_GameState)(nil),
		(*ServerEvent_ChatMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
